### ISSUE TITLE
[Todo: Update] Vuejs Section

### ISSUE THREAD

**Issue by chestercolita** [chestercolita/til#31]
# Reference
https://vuejs.org/v2/guide/

# Add Learnings
- [ ] List Rendering
- [ ] Template Syntax
- [ ] Event Handlings
- [ ] Form Input Bindings
- [ ] Conditional Rendering
- [ ] Class and Style Bindings
- [ ] Computed Properties and Watchers
- [ ] Lifecycle Hooks
