### ISSUE TITLE
[Todo: Update] Nuxtjs

### ISSUE THREAD

**Issue by chestercolita** [chestercolita/til#32]
# Reference
https://nuxtjs.org/docs/get-started/installation/

# Add Learnings
- [ ] Rendering
- [ ] Deployment Targets
- [ ] Data Fetching
- [ ] Meta Tags and SEO
- [ ] Configuration
- [ ] Built-in Components
- [ ] Component Discovery
- [ ] Transitions
- [ ] Directory Structures: page, assets, modules, middleware, etc.
- [ ] fetch hook
